### ISSUE TITLE
配置数据及基础表数据脚本

### ISSUE THREAD

**Issue by Eric-xgc** [DestinyCore/Destiny.Core.Flow#10]

**Comment by lurudong** [comment]
你的，是什么数据库？MYSQL还是

**Comment by lurudong** [comment]
假如是MYSQL的，你可以到dhg下https://github.com/DestinyCore/Destiny.Core.Flow/tree/dhg/src/Destiny.Core.Flow.API/db 
数据脚本。目前该分支还没有合并 主支上。

**Comment by Eric-xgc** [comment]
有sql server的版本吗？

**Comment by lurudong** [comment]
你sql server什么版本的？

**Comment by Eric-xgc** [comment]
2014版本的

**Comment by lurudong** [comment]
目前这边还没有支持sql server,我们这边会根据这个问题，进行支持的。

**Comment by Eric-xgc** [comment]
好滴，谢谢你

**Comment by lurudong** [comment]
不用客气，支持好，第一时间通知你。。

**Comment by lurudong** [comment]
你拉下dhg分支，支持了sql server，

**Comment by lurudong** [comment]
已合并主分支上了，你修改下配置文件
修改成
![image](https://user-images.githubusercontent.com/44517714/102013328-478aec00-3d8a-11eb-8263-07edc3b0584d.png)
就可以了

**Comment by Eric-xgc** [comment]
收到谢谢
