### ISSUE TITLE
DestinyCoreDb.txt这样配置数据连接字符还是第一次见过，不太会

### ISSUE THREAD

**Issue by Eric-xgc** [DestinyCore/Destiny.Core.Flow#11]
你好，配置数据库连接，怎么跑起来还是有点不太会，操作文档和开发文档不够，博客内容也不多。

**Comment by GeorGeWzw** [comment]
@Eric-xgc 你可以把配置的XXXXX.txt换成你自己的链接字符串；
![image](https://user-images.githubusercontent.com/46982191/104191198-29331180-5458-11eb-90e4-dcbf6b5e5dcb.png)
只需要把这块代码删掉就可以了

**Comment by lurudong** [comment]
1.链接字符串可以配置成
Data Source= xxx;Initial Catalog=Test001;User ID=luyun;Password=xxx.;MultipleActiveResultSets=true
DestinyCoreDb.txt 这样我们就是把链接写在文件中，因为数据库链接是放在服务器， 不想对外暴露出去，才写到文本中的
你把DestinyCoreDb.txt 改成对应的链接字符串（Data Source= xxx;Initial Catalog=Test001;User ID=luyun;Password=xxx.;MultipleActiveResultSets=true），还有数据库类型
2.因为时间问题，还要开发其他项目，操作文档日后补上，有可能等工作流开发完，补上。

**Comment by Eric-xgc** [comment]
收到谢谢😊

**Comment by GeorGeWzw** [comment]
> 收到谢谢😊

你可以加一下群（980
![image](https://user-images.githubusercontent.com/46982191/104192249-85e2fc00-5459-11eb-8675-a9877e54ca2e.png):
980386066）

**Comment by lurudong** [comment]
@Eric-xgc  不用改代码，改配置文件就可以了
