### ISSUE TITLE
请问后台的用户名和密码

### ISSUE THREAD

**Issue by CHENJKNB** [DestinyCore/Destiny.Core.Flow#8]
大佬方便告诉一下 后台的用户名和密码吗？用你 文档的里面的 登录不了。 谢谢

**Comment by GeorGeWzw** [comment]
> 大佬方便告诉一下 后台的用户名和密码吗？用你 文档的里面的 登录不了。 谢谢
框架再迁移到ids4，改动量有点大，升级版本下周就可以用了

**Comment by GeorGeWzw** [comment]
@CHENJKNB 后台框架再迁移到IdentityServer4，因为需要重写IdentityServer4的一些东西，底层改动量有点大，在线版本的下周就可以用了，若是你Clone的代码的话，默认账号：admin;密码：123456

**Comment by joesdu** [comment]
> @CHENJKNB 后台框架再迁移到IdentityServer4，因为需要重写IdentityServer4的一些东西，底层改动量有点大，在线版本的下周就可以用了，若是你Clone的代码的话，默认账号：admin;密码：123456

谢谢大佬.

**Comment by lurudong** [comment]
@CHENJKNB 线上的可以正常访问了
